name: Continuous delivery 1.0

on:
    push:
        branches:
            - develop
 
env:
  IMAGE_NAME: simple-api-java
  AZURE_WEBAPP_NAME: simple-api-java
 
jobs:
    build:
        runs-on: ubuntu-latest
        steps:             
        -  
            name: Git Checkout 
            uses: actions/checkout@v4 
 
        -   name: Setup Java SDK 
            uses: actions/setup-java@v4 
            with: 
              distribution: 'temurin'  
              java-version: '21'

        -   name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

        -   name: Build and Push Docker Image
            uses: docker/build-push-action@v6 
            with: 
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
        - 
            name: Azure Login
            uses: azure/login@v1
            with:
              creds: ${{ secrets.AZURE_CREDENTIALS }}

        - 
            name: Deploy to Azure Web App
            uses: azure/webapps-deploy@v2
            with:
              app-name: 'fiap-simple-api-dev0'
              publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
              images: '${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest'
